### PR TITLE
Unavailable bonus points achivements cause client side exception

### LINKED ISSUE #917: Unavailable bonus points achivements cause client side exception

### PR DESCRIPTION
**Pull request by nyet-ty**
Resolve #917 

## PR includes

-   [x] Bug Fix

### CODE REVIEW

**Review by 9teen90nine — APPROVED** [review]

File: src/modules/bonusPointsMethods.ts [hunk 1]
```diff
@@ -103,8 +103,22 @@ export const bonusPointsMethods = {
...
+            Sentry.captureException(`BonusPointsAchievement error ${response.statusText}`);
+        }
+
         const json = await response.json();
-        const items: BonusPointsAchievement[] = json.data;
+        const items: BonusPointsAchievement[] = json.data || [];
+
+        if (items.some((item) => !item.attributes.achievment_category?.data?.id)) {
+            Sentry.captureException(
+                `BonusPointsAchievements does not have achievenemt cathegory ${items
```
Comment (tsumo) [inline src/modules/bonusPointsMethods.ts:116]: Typos:
Achievement 
Category

**Review by tsumo — APPROVED** [review]
