### PR TITLE
User picker in user edit form is broken

### LINKED ISSUE #321: User picker in user edit form is broken
1) it's open by default
2) looks bad - doesn't fit content

### PR DESCRIPTION
**Pull request by tsumo**
## PR includes

-   [x] Bug Fix

## Related issues

Resolve #321

### CODE REVIEW

**Review by Katrin-kudryash — APPROVED** [review]

File: src/components/UserSupervisorEditable/UserSupervisorEditable.tsx [hunk 1]
```diff
@@ -28,21 +30,25 @@ export const UserSupervisorEditable = ({ onChange }: UserSupervisorEditableProps
...
+                    ))}
                     placeholder={tr('Choose a supervisor')}
                     autoFocus
                     size="m"
                     autoComplete="off"
-                    value={value ?? search}
+                    value={value ?? selectedSupervisor?.name}
                     onChange={(e) => {
-                        setSelectedSupervisor(undefined);
+                        setSelectedSupervisor(null);
```
Comment (nyet-ty) [inline src/components/UserSupervisorEditable/UserSupervisorEditable.tsx:49]: Why do we need set supervisor null in input onChange?

**Review by nyet-ty — CHANGES_REQUESTED** [review]

File: src/components/UserSupervisorEditable/UserSupervisorEditable.tsx (hunk 1 above)
Comment (tsumo) [reply src/components/UserSupervisorEditable/UserSupervisorEditable.tsx]: You have a selected user
You start to erase the name
Input reacts by unassigning current user, since the name doesn't match anymore

**Review by 9teen90nine — APPROVED** [review]

**Review by nyet-ty — APPROVED** [review]
